# -*- coding: utf-8 -*-
"""ML_LabAss7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13lEo0phIpxvacPYsTqMdBiC_PgOcg4SQ
"""

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

iris = datasets.load_iris()
X = iris.data
y = iris.target
target_names = iris.target_names

print("Feature shape:", X.shape)
print("Target classes:", target_names)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = SVC(kernel='linear', C=1.0)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=target_names))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))