# -*- coding: utf-8 -*-
"""ML_lab_KmeansClustering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lcozVTCA97VjooAUzkqECm-RZy8SpxpK
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

data = pd.read_excel("/content/EastWestAirlines.xlsx")
data.head()

data.info()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)
type(data_scaled)

kmeans = KMeans(n_clusters=4, random_state=0)
kmeans.fit(data_scaled)

"""# inertia value for 2 clusters"""

kmeans.inertia_

"""# inertia value for 3 clusters"""

kmeans.inertia_

"""# inertia value for 4 clusters"""

kmeans.inertia_

kmeans.cluster_centers_

kmeans.labels_[10:20]

acc = []
for i in range(1, 21):
    kmeans = KMeans(n_clusters=i, random_state=0)
    kmeans.fit(data_scaled)
    acc.append(kmeans.inertia_)
acc

plt.plot(range(1, 21), acc)
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('Accuracy')
plt.show()

"""# Building cluster algorithm"""

from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=7, random_state=40)
kmeans.fit(data_scaled)