# -*- coding: utf-8 -*-
"""MLlab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AfX19zeoBPoVqr1zcy7fEAnrIcm-Qz-I
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv

data = [[100,54,2],
        [150,67,1],
        [123,78,3],
        [144,98,5]]
data = pd.DataFrame(data)
data.describe()

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)
scaled_data

data

from sklearn.preprocessing import Normalizer
scalar_normalisation = Normalizer()
scaled_data = scalar_normalisation.fit_transform(data)
scaled_data

import sklearn.preprocessing
from sklearn.preprocessing import StandardScaler
scaler_stdscale = StandardScaler()
scaled_data = scaler_stdscale.fit_transform(data)
scaled_data

v1=pd.DataFrame(scaled_data)
v1.describe()