# -*- coding: utf-8 -*-
"""MLlab_ass4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbCWD4jUsqbUiOIiNGjuCRQWRdgni8Dd
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = pd.read_csv("/content/employees.csv")

df.fillna(df.mode().iloc[0], inplace=True)
label_enc = LabelEncoder()
for col in df.select_dtypes(include=['object']).columns:
    df[col] = label_enc.fit_transform(df[col])
X = df.drop(columns=['Senior Management'])
y = df['Senior Management'].astype(int)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print("Confusion Matrix:\n", conf_matrix)